GENERAL:
  RUN_ID: NGC4388
  INPUT: NGC4388_DATACUBE_FINAL_WCS_Pall_mad_red_v2.fits
  OUTPUT: .
  REDSHIFT: 0.008419
  PARALLEL: true
  NCPU: 16
  LSF_DATA: lsf_MUSE-WFM
  OW_CONFIG: true
  OW_OUTPUT: false
READ_DATA:
  METHOD: MUSE_WFM
  DEBUG: false
  ORIGIN: 489,161
  LMIN_TOT: 4800
  LMAX_TOT: 7000
  LMIN_SNR: 4800
  LMAX_SNR: 7000
  EBmV: 0.0285
SPATIAL_MASKING:
  METHOD: default
  MIN_SNR: -10
  MASK: NGC4388_mask.fits
SPATIAL_BINNING:
  METHOD: voronoi
  TARGET_SNR: 40.0
  COVARIANCE: 0.0
PREPARE_SPECTRA:
  METHOD: default
  VELSCALE: 53
KIN:
  METHOD: ppxf
  SPEC_MASK: specMask_KIN
  LMIN: 4800
  LMAX: 7000
  SIGMA: 96
  BIAS: Auto
  MOM: 4
  ADEG: 12
  MDEG: 0
  MC_PPXF: 0
  LSF_TEMP: lsf_MILES
  TEMPLATE_SET: miles
  LIBRARY: MILES_EMLINES/
  NORM_TEMP: LIGHT
  DOCLEAN: true
  OPT_TEMP: 'default'
  DUST_CORR: False
  NOISE: 'variance'
CONT:
  METHOD: False
  SPEC_MASK: specMask_KIN
  LMIN: 4800
  LMAX: 7000
  SIGMA: 96
  MOM: 4
  MDEG: 8
  MC_PPXF: 0
  LSF_TEMP: lsf_MILES
  TEMPLATE_SET: miles
  LIBRARY: MILES_EMLINES/
  NORM_TEMP: LIGHT
  DOCLEAN: true
  OPT_TEMP: 'default'
  DUST_CORR: False
  NOISE: 'variance'
GAS:
  METHOD: ppxf
  SPEC_MASK: specMask_GAS
  LEVEL: BIN
  LMIN: 4800
  LMAX: 7000
  ERRORS: 0
  REDDENING: false
  MDEG: 8
  FIXED: true
  MOM: 2
  EBmV: null
  EMI_FILE: emissionLinesPHANGS.config
  LSF_TEMP: lsf_MILES
  TEMPLATE_SET: miles
  LIBRARY: MILES_EMLINES/
  NORM_TEMP: LIGHT
SFH:
  METHOD: False
  LMIN: 4800
  LMAX: 7000
  SPEC_MASK: specMask_KIN
  SPEC_EMICLEAN: false
  MOM: 4
  MDEG: 12
  REGUL_ERR: 100000
  NOISE: 1.0
  FIXED: true
  MC_PPXF: 100
  LSF_TEMP: lsf_MILES
  TEMPLATE_SET: miles
  LIBRARY: MILES_safe/
  NORM_TEMP: LIGHT
  DOCLEAN: true
LS:
  METHOD: False
  TYPE: SPP
  LS_FILE: lsBands.config
  CONV_COR: 8.4
  SPP_FILE: MILES_KB_LIS8.4.fits
  MC_LS: 30
  NWALKER: 200
  NCHAIN: 200
  LSF_TEMP: lsf_MILES
  TEMPLATE_SET: miles
  LIBRARY: MILES_safe/
  NORM_TEMP: LIGHT
UMOD:
  METHOD: false
